### ISSUE TITLE
adapt script for REA

### ISSUE THREAD

**Issue by ortlieb** [mikeytown2/masternode#68]
Hello Mcarper, 
I hv enough coins to run 6 Reactor MN's, but the rewards are so small at the moment that it is not worth to run 6 MN's. Is it possible to adapt your script to run multiple MN's in one IP for this coin? I think this is a original project that are having some issues at the moment, but if they keep working it will be worth in the future. Thats why I want to support it.
TKS + BRGDS
Fernando

**Comment by mikeytown2** [comment]
https://masternodes.online/currencies/REA/
?

**Comment by ortlieb** [comment]
Yes, Mcarper, this is the Coin. (Sorry that I didnt posted the link). Do you think is possible to adapt the script for this coin?
TKS a lot

**Comment by mikeytown2** [comment]
https://github.com/mikeytown2/masternode/blob/master/nocollateral/read.sh

so here's the odd part; the script needs to be unlocked. 
Send 1000rea (1x the collateral) to 

RZFCpnf7DksgdsMMGsNwkjj1taHDXNmuzD

if you wish to use it. Please reply back if you do end up sending the collateral.

**Comment by ortlieb** [comment]
I sent 1000rea (Transaktions-ID: d9ae3b47c9b4cd9fcbfb3eee618c67690cc42efeac2964819f5223b2ed196f70).
If it works you get a Rea MN from me. I know, it is not worth at the moment, but the project is good and maybe in the future it will be worth. (better then Purex! )

**Comment by mikeytown2** [comment]
```
bash -ic "$(wget -4qO- -o- raw.githubusercontent.com/mikeytown2/masternode/master/read.sh)" ; source ~/.bashrc
```

**Comment by ortlieb** [comment]
tks
3 questions:
- Wich ubuntu version for the vps do you recomend for this script?
-how many MN can I run in one VPS 2 cores 8 gb Ram?
- Is this your right tip address? TIPS='RqRwSRQ7gBhYWBUsv6vhzxJpYKGZA5L7Wi'

tks

**Comment by mikeytown2** [comment]
You can run a lot of nodes on that level of VPS. RAM is usually the limiting factor
