### ISSUE TITLE
Pls add DT3 

### ISSUE THREAD

**Issue by DreamTeamCoin3** [mikeytown2/masternode#70]
Would you pls be so kind to do a Daemon MN on Linux setup guide for DT3?
https://github.com/DreamTeamCoin3/DT3
Discord: https://discord.gg/uwE53Z4

**Comment by mikeytown2** [comment]
Do you have a block explorer ?

**Comment by DreamTeamCoin3** [comment]
Block explorer: http://explorer.crypto-dreamteam.com/
The rest is here: https://github.com/DreamTeamCoin3/DT3/releases  idk if there is a Linux binary release ...lol ..if not there, where can i get it?

**Comment by DreamTeamCoin3** [comment]
I just see the source

**Comment by mikeytown2** [comment]
Think someone on your team can upload the binary files to GitHub or your website?

**Comment by mikeytown2** [comment]
Closing as script is out
