### ISSUE TITLE
Pls add LGS

### ISSUE THREAD

**Issue by snowgarvan3** [mikeytown2/masternode#88]

**Comment by mikeytown2** [comment]
Are you or a group of you willing to provide the collateral?

**Comment by snowgarvan3** [comment]
Yes Im .

**Comment by mikeytown2** [comment]
Send to 
Gc2sDqRfnM3Qc4aqGi9GtkXVGBKKZNAfUD
Let me know when sent; will upload the script once I see the tx.

**Comment by snowgarvan3** [comment]
okay done

**Comment by mikeytown2** [comment]
Should be out now and working
